src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 * @UniqueEntity(fields={"contact"}, message="Ce contact est deja utilisé !")
 */
class Client implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenoms;

    /**
     * @ORM\Column(type="datetime", )
     */
    private $create_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_actif;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $commune;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $solde;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contact;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenoms(): ?string
    {
        return $this->prenoms;
    }

    public function setPrenoms(string $prenoms): self
    {
        $this->prenoms = $prenoms;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getIsActif(): ?bool
    {
        return $this->is_actif;
    }

    public function setIsActif(bool $is_actif): self
    {
        $this->is_actif = $is_actif;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getSolde(): ?int
    {
        return $this->solde;
    }

    public function setSolde(?int $solde): self
    {
        $this->solde = $solde;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setContact(string $contact): self
    {
        $this->contact = '225'.$contact;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return string[] The user roles
     */
    public function getRoles()
    {
        return ['ROLE_CLIENT'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenoms')
            ->add('create_at')
            ->add('password', PasswordType::class)
            ->add('address')
            ->add('is_actif')
            ->add('commune')
            ->add('solde')
            ->add('contact')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $encoder): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $client->setPassword($encoder->encodePassword($client, $client->getPassword()));

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index');
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-sm btn-red rounded-pill">Delete</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-green rounded-pill">{{ button_label|default('Enregister') }}</button>
{{ form_end(form) }}

templates/client/edit.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Modifier le client{% endblock %}

{% block content %}
    <h1>Modification</h1>

    <div class="w-50">
        {{ include('client/_form.html.twig', {'button_label': 'Modifier'}) }}

        <div class="d-flex mt-3">
            <a href="{{ path('client_index') }}" class="btn btn-sm btn-blue rounded-pill">Revenir a la liste</a>

            {{ include('client/_delete_form.html.twig') }}
        </div>

    </div>

{% endblock %}

templates/client/index.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}gestion des clients{% endblock %}

{% block content %}
<div ng-app="app">

    <h1>Liste des clients</h1>
    <div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenoms</th>
                <th>Date d'adhesion</th>
                <th>Address</th>
                <th>Actif</th>
                <th>Commune</th>
                <th>Solde</th>
                <th>Contact</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.nom }}</td>
                <td>{{ client.prenoms }}</td>
                <td>{{ client.createAt ? client.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ client.address }}</td>
                <td>{{ client.isActif ? 'Yes' : 'No' }}</td>
                <td>{{ client.commune }}</td>
                <td>{{ client.solde }}</td>
                <td>{{ client.contact }}</td>
                <td>
                    <a href="{{ path('client_show', {'id': client.id}) }}"><span class="fa fa-eye"></span></a>
                    <a href="{{ path('client_edit', {'id': client.id}) }}"><span class="fa fa-edit"></span></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">Aucun client</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('client_new') }}" class="btn btn-sm btn-blue rounded-pill">Nouveau client <span class="fa fa-plus"></span></a>
</div>
{% endblock %}

{% block javascript %}

let app = angular.module('app', [])

{% endblock %}

templates/client/new.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Nouveau Client{% endblock %}

{% block content %}
    <h1>Creer un nouveau client</h1>
    <hr>
    <div class="w-50">
        {{ include('client/_form.html.twig') }}

    </div>

    <a href="{{ path('client_index') }}" class="btn btn-sm btn-blue rounded-pill">Revenir à la liste</a>
{% endblock %}

templates/client/show.html.twig
{% extends 'admin/index.html.twig' %}

{% block title %}Client-{{ client.id }}{% endblock %}

{% block content %}
    <h1>Details client</h1>

    <table class="table">
        <tbody>

        </tbody>
    </table>

    <div class="jumbotron">
        <div class="d-flex align-items-center">
            <div>
                <span class="fa fa-user-circle black-ic fa-4x"></span>
            </div>
            <div class="ml-4 flex-grow-1">
                <h3>{{ client.prenoms }} {{ client.nom }}</h3>
            </div>
            <div>
                <a href="{{ path('client_index') }}" class="btn btn-sm btn-blue rounded-pill">back to list</a>

                <a href="{{ path('client_edit', {'id': client.id}) }}" class="btn btn-sm btn-blue rounded-pill">edit</a>
            </div>
        </div>
        <p></p>
        <div class="d-flex">
            <div class="w-50">
                <table class="table">
                    <tr>
                        <th><b>Nom</b></th>
                        <td>{{ client.nom }}</td>
                    </tr>
                    <tr>
                        <th><b>Prenoms</b></th>
                        <td>{{ client.prenoms }}</td>
                    </tr>
                    <tr>
                        <th><b>Date d'adhesion</b></th>
                        <td>{{ client.createAt ? client.createAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th><b>Address</b></th>
                        <td>{{ client.address }}</td>
                    </tr>
                </table>
            </div>
            <div class="w-50">
                <table class="table">
                    <tr>
                        <th><b>Is_actif</b></th>
                        <td>{{ client.isActif ? 'Yes' : 'No' }}</td>
                    </tr>
                    <tr>
                        <th><b>Commune</b></th>
                        <td>{{ client.commune }}</td>
                    </tr>
                    <tr>
                        <th><b>Solde</b></th>
                        <td>{{ client.solde }}</td>
                    </tr>
                    <tr>
                        <th><b>Contact</b></th>
                        <td>{{ client.contact }}</td>
                    </tr>
                </table>
            </div>
        </div>
        <div>
            {{ include('client/_delete_form.html.twig') }}
        </div>
    </div>




{% endblock %}